//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeretPreWorkControl
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_notifications
    {
        public int ID { get; set; }
        public Nullable<int> Deparment_id { get; set; }
        public Nullable<int> is_notified { get; set; }
        public Nullable<int> order_id { get; set; }
        public string sales_agent_name { get; set; }
    
        public virtual tbl_user_groups tbl_user_groups { get; set; }
        public virtual tbl_orders tbl_orders { get; set; }
    }
}
