//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeretPreWorkControl
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_action_to_dept
    {
        public int ID { get; set; }
        public int action_ID { get; set; }
        public int recieved_department_ID { get; set; }
    
        public virtual tbl_sla_actions tbl_sla_actions { get; set; }
        public virtual tbl_user_groups tbl_user_groups { get; set; }
    }
}
